/*
 * ultraSound_driver.c
 *
 *  Created on: Oct 19, 2023
 *      Author: Shorouk Shawky
 */

#include "gpio.h"
#include "icu.h"
#include "ultraSound_driver.h"
#include <util/delay.h>
#include <math.h>

/*Global Variables*/
static uint8 g_edgeCount = 0;
static volatile uint16 g_time = 0;



ICU_ConfigType ICU_Configurations={F_CPU_8,RAISING};


/*function protptype*/
/*Discription:
 * Initialize the ICU driver as required.
 * Setup the ICU call back function.
 *  setup the direction for the trigger pin as output pin through the GPIO driver.
 *
 */
void Ultrasonic_init(void){
	ICU_init(&ICU_Configurations);
	ICU_setCallBack(Ultrasonic_edgeProcessing);
	GPIO_setupPinDirection(PORTB_ID,PIN5_ID,PIN_OUTPUT);
	GPIO_writePin(PORTB_ID, PIN5_ID,LOGIC_LOW);
}


/*Discription:
 * Send the Trigger pulse to the ultrasonic
 */
void Ultrasonic_Trigger(void){
	GPIO_writePin(PORTB_ID,PIN5_ID,LOGIC_HIGH);
	_delay_us(10);
	GPIO_writePin(PORTB_ID,PIN5_ID,LOGIC_LOW);


}


/*Discription:
 *  Send the trigger pulse by using Ultrasonic_Trigger function.
 *  Start the measurements by the ICU from this moment.
 *   Return: The measured distance in Centimeter.
 */
uint16 Ultrasonic_readDistance(void){

	uint16 distance=0;
	Ultrasonic_Trigger();

	distance=g_time *0.017;
	return distance;

}
/*Discription:
 * This is the call back function called by the ICU driver.
 * This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
 *
 */
void Ultrasonic_edgeProcessing(void)
{
	g_edgeCount++;
	if(g_edgeCount == 1)
	{
		/*
		 * Clear the timer counter register to start measurements from the
		 * first detected rising edge
		 */
		ICU_clearTimerValue();
		/* Detect falling edge */
		ICU_setEdgeDetectionType(FALLING);
	}
	else if(g_edgeCount == 2)
	{
		/* Store the High time value */
		g_time = ICU_getInputCaptureValue();
		/* Detect rising edge */
		ICU_clearTimerValue();
		ICU_setEdgeDetectionType(RAISING);
		g_edgeCount=0;
	}


}

